name = "minimal_containers"
description = "Shiny new project"
version = "0.1.1-dev"

authors = ["Simon Wright"]
maintainers = ["Simon Wright <simon@pushface.org>"]
maintainers-logins = ["simonjwright"]
